# Generated by Django 4.0 on 2021-12-16 14:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phonenumber', models.CharField(max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(max_length=100)),
                ('delive', models.BooleanField(default=False)),
                ('create', models.DateTimeField(default=datetime.datetime(2021, 12, 16, 21, 9, 5, 605180))),
                ('cart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart', to='profiles.cart')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pictures')),
                ('name', models.CharField(default='', max_length=100)),
                ('number_phone', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=500)),
                ('pub_date', models.DateField(default=datetime.date.today, verbose_name='Birthday')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='OrderSideDishes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderside', to='profiles.order')),
                ('sidess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sidess', to='project.sidedishes')),
            ],
        ),
        migrations.CreateModel(
            name='OrderPizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderpizza', to='profiles.order')),
                ('pizaa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pizaa', to='project.pizza')),
            ],
        ),
        migrations.CreateModel(
            name='OrderCombo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=1)),
                ('combobox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combobox', to='project.combo')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordercombo', to='profiles.order')),
            ],
        ),
    ]
