# Generated by Django 3.2.7 on 2021-12-12 16:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='create',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 12, 23, 44, 21, 907010)),
        ),
    ]
