# Generated by Django 3.2.7 on 2021-12-09 10:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='create',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 9, 17, 36, 46, 373995)),
        ),
    ]
