# Generated by Django 3.2.7 on 2021-11-07 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='desciption',
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='number_phone',
            field=models.CharField(default='000000000', max_length=10),
        ),
    ]
