# Generated by Django 3.2.7 on 2021-11-22 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='combo',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='comboamount',
            options={'ordering': ('combo', 'pizza', 'dishes')},
        ),
        migrations.AlterModelOptions(
            name='pizza',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='topping',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='comboamount',
            name='combo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combo', to='project.combo'),
        ),
        migrations.AlterField(
            model_name='comboamount',
            name='dishes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dishes', to='project.sidedishes'),
        ),
        migrations.AlterField(
            model_name='comboamount',
            name='pizza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pizza', to='project.pizza'),
        ),
        migrations.AlterField(
            model_name='toppingamount',
            name='topping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topping_amount', to='project.topping'),
        ),
    ]
