# Generated by Django 3.2.7 on 2021-12-09 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreSide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5)),
                ('side', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sidescore', to='project.sidedishes')),
            ],
        ),
        migrations.CreateModel(
            name='ScorePizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5)),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pizzascore', to='project.pizza')),
            ],
        ),
        migrations.CreateModel(
            name='ScoreCombo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5)),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comboscore', to='project.combo')),
            ],
        ),
    ]
