# Generated by Django 3.2.7 on 2021-12-12 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='combo',
            name='percent',
            field=models.IntegerField(default=10),
        ),
    ]
